export const houseProjects = [
	{
		name: 'Nafis',
		location: 'Margilon shahar',
		volume: 2343,
		direction: 'Turar joy majmuasi',
		image: '/imgs/tosh.webp',
		status: 'Tez kunda',
	},
	{
		name: 'Margilon city',
		location: 'Margilon shahar',
		volume: 2343,
		direction: 'Turar joy majmuasi',
		image: '/imgs/margilonciti.webp',
		status: 'Tez kunda',
	},
	{
		name: 'Komfort',
		location: 'Fargona shahar',
		volume: 1483,
		direction: 'Turar joy majmuasi',
		image: '/imgs/uzbe.jpeg',
		status: 'Yakunlangan',
	},
	{
		name: 'Nur Kompleks',
		location: 'Fargona shahar',
		volume: 1483,
		direction: 'Turar joy majmuasi',
		image: '/imgs/nurc.webp',
		status: 'Tez kunda',
	},
	{
		name: 'Sakinat',
		location: 'Fargona shahar',
		volume: 1483,
		direction: 'Turar joy majmuasi',
		image: '/imgs/sakinat.webp',
		status: 'Yakunlangan',
	},
	{
		name: 'Margilon city',
		location: 'Margilon shahar',
		volume: 2343,
		direction: 'Turar joy majmuasi',
		image: '/imgs/hero.png',
		status: 'Tez kunda',
	},
]
